#!/bin/bash

set -e

exec 3>&1
exec 1>&2

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > $payload <&0

webhook_url=$(jq -r '.source.url' < $payload)

body=$(echo "{\"pipeline\":\"${BUILD_PIPELINE_NAME}\",\"job\":\"${BUILD_JOB_NAME}\",\"build\":\"${BUILD_ID}\"}" | jq -c "")

curl -s -X POST -H 'Content-type: application/json' --data "$body" $webhook_url

jq -n '{"version":{"ref":"0"}}' >&3

